week-7
petrNikolaev1/Smart-Chat pull request #4
Opened 2018-10-27 09:34 UTC by petrNikolaev1

Selecting the interface language support added

2018-10-29 12:56 UTC, kos33rd requested changes
По заданиям седьмой недели необходимо помимо прочего подключить к проекту одну из библиотек работы с формами.

2018-10-29 12:56 UTC, kos33rd commented on client/src/assets/styles/Select.scss
> +.css-rsyb7x {
Данный стиль не используется нигде в приложении. 
Для чего он тут?

2018-10-31 08:25 UTC, impecablemee commented on client/src/assets/styles/Select.scss
> +.css-rsyb7x {
А react-select не является библиотекой по работе с формами? Я спрашивал об этом у вас в телеграме. Данный стиль нужен для корректного отображения react-select формы.

2018-11-02 17:55 UTC, kos33rd commented on client/src/assets/styles/Select.scss
> +.css-rsyb7x {
Так, да... react-select.
Я по началу в telegram неправильно понял. Сейчас ещё раз посмотрел, что за зверь - думаю, для базовой работы с формой ОК. Тогда претензий нет

2018-11-02 17:55 UTC, kos33rd approved these changes

2018-11-08 17:08 UTC, merged